services:
  database:
    image: postgres:17-bookworm
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_LISTEN_ADDRESSES: "*"
    volumes:
      - local-postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      ENV: ${ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSLMODE: disable
      STRIPE_KEY: ${STRIPE_KEY}
    depends_on:
      - database

  frontend:
    build:
      context: ../flockcounter-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8080/api
        NEXT_PUBLIC_TEST_STRIPE_KEY: ${NEXT_PUBLIC_TEST_STRIPE_KEY}
    ports:
      - 3000:3000
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      BACKEND_URL: http://backend:8080/api
    depends_on:
      - backend

volumes:
  local-postgres-data:
    external: true
